# Generated by Django 3.2.6 on 2021-08-12 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50)),
                ('kcal', models.IntegerField()),
                ('carboidratos', models.IntegerField()),
                ('proteinas', models.IntegerField()),
                ('gorduras', models.IntegerField()),
                ('quantidade', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Medida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=30)),
                ('abreviacao', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='TipoRefeicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Refeicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField(auto_now_add=True)),
                ('tipo_refeicao', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='alimentacao.tiporefeicao')),
            ],
        ),
        migrations.CreateModel(
            name='Porcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('alimento', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='alimentacao.alimento')),
                ('refeicao_alimento', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='alimentacao.refeicao')),
            ],
        ),
        migrations.AddField(
            model_name='alimento',
            name='medida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='alimentacao.medida'),
        ),
    ]
