# Generated by Django 3.2.6 on 2021-08-12 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alimentacao', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='porcao',
            options={'verbose_name_plural': 'porções'},
        ),
        migrations.AlterModelOptions(
            name='refeicao',
            options={'verbose_name_plural': 'refeições'},
        ),
        migrations.AlterModelOptions(
            name='tiporefeicao',
            options={'verbose_name_plural': 'tipos de refeições'},
        ),
        migrations.AlterField(
            model_name='alimento',
            name='carboidratos',
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
        migrations.AlterField(
            model_name='alimento',
            name='gorduras',
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
        migrations.AlterField(
            model_name='alimento',
            name='proteinas',
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
    ]
