# Generated by Django 3.2.6 on 2021-08-12 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alimentacao', '0002_auto_20210812_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='porcao',
            name='refeicao_alimento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='porcoes', to='alimentacao.refeicao'),
        ),
    ]
